<a href="https://colab.research.google.com/github/bhaghighi/Deep-Learning-101/blob/master/Pytorch_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Building custom dataset***


In [11]:
import os 
import torch
import torch.nn as nn 
from torch.nn import functional as F 
import numpy as np 
from torch.utils.data import TensorDataset

# create simple numpy array to test custom data set
x = torch.from_numpy(np.array([1, 2, 3, 4, 5])).float()
y = torch.from_numpy(np.array([11, 22, 33, 44, 55])).float()

In [12]:
# First approach:
from torch.utils.data import TensorDataset
train_data1 = TensorDataset(x, y)
print (type(train_data1))
for i, j  in train_data1:
    print (i,j)

torch.utils.data.dataset.TensorDataset
tensor(1.) tensor(11.)
tensor(2.) tensor(22.)
tensor(3.) tensor(33.)
tensor(4.) tensor(44.)
tensor(5.) tensor(55.)


In [13]:
# Second approach:
from torch.utils.data import Dataset 

class CustomDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def __getitem__(self, index):
        return (self.x[index], self.y[index])

    def __len__(self):
        return len(self.x)
    
train_data2 = CustomDataset(x, y)
print (type(train_data2))

for i,j in train_data2:
    print (i,j)

__main__.CustomDataset
tensor(1.) tensor(11.)
tensor(2.) tensor(22.)
tensor(3.) tensor(33.)
tensor(4.) tensor(44.)
tensor(5.) tensor(55.)


In [14]:
# What approach? first or second and why? 
# can we use them in DataLoeader? what is the point of DataLoader? 

In [15]:
# using train_data1 with DataLoader 
from torch.utils.data import DataLoader
# try to run this with differnt batch sizes? 
train_loader = DataLoader(dataset=train_data1, batch_size=2, shuffle=False)
for i, j in train_loader:
    print (i,j)

tensor([1., 2.]) tensor([11., 22.])
tensor([3., 4.]) tensor([33., 44.])
tensor([5.]) tensor([55.])


In [16]:
# using train_data2 with DataLoader 
from torch.utils.data import DataLoader
# try to run this with differnt batch sizes? 
train_loader = DataLoader(dataset=train_data2, batch_size=2, shuffle=False)
for i, j in train_loader:
    print (i,j)

tensor([1., 2.]) tensor([11., 22.])
tensor([3., 4.]) tensor([33., 44.])
tensor([5.]) tensor([55.])
