<a href="https://colab.research.google.com/github/bhaghighi/Deep-Learning-101/blob/master/Pytorch_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Building custom dataset***

---




1- Building Costum Data set (two ways)

In [ ]:
import os 
import torch
import torch.nn as nn 
from torch.nn import functional as F 
import numpy as np 
from torch.utils.data import TensorDataset

# create simple numpy array to test custom data set
x = torch.from_numpy(np.array([1, 2, 3, 4, 5])).float()
y = torch.from_numpy(np.array([11, 22, 33, 44, 55])).float()

In [ ]:
# First approach:
from torch.utils.data import TensorDataset
train_data1 = TensorDataset(x, y)
print (type(train_data1))
for i, j  in train_data1:
    print (i,j)

torch.utils.data.dataset.TensorDataset
tensor(1.) tensor(11.)
tensor(2.) tensor(22.)
tensor(3.) tensor(33.)
tensor(4.) tensor(44.)
tensor(5.) tensor(55.)


In [ ]:
# Second approach:
from torch.utils.data import Dataset 

class CustomDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def __getitem__(self, index):
        return (self.x[index], self.y[index])

    def __len__(self):
        return len(self.x)
    
train_data2 = CustomDataset(x, y)
print (type(train_data2))

for i,j in train_data2:
    print (i,j)

__main__.CustomDataset
tensor(1.) tensor(11.)
tensor(2.) tensor(22.)
tensor(3.) tensor(33.)
tensor(4.) tensor(44.)
tensor(5.) tensor(55.)


2- Using Costum Data set with DataLoader 

In [ ]:
# What approach? first or second and why? 
# can we use them in DataLoeader? what is the point of DataLoader? 

In [ ]:
# using train_data1 with DataLoader 
from torch.utils.data import DataLoader
# try to run this with differnt batch sizes? 
train_loader = DataLoader(dataset=train_data1, batch_size=2, shuffle=False)
for i, j in train_loader:
    print (i,j)

tensor([1., 2.]) tensor([11., 22.])
tensor([3., 4.]) tensor([33., 44.])
tensor([5.]) tensor([55.])


In [ ]:
# using train_data2 with DataLoader 
from torch.utils.data import DataLoader
# try to run this with differnt batch sizes? 
train_loader = DataLoader(dataset=train_data2, batch_size=2, shuffle=False)
for i, j in train_loader:
    print (i,j)

tensor([1., 2.]) tensor([11., 22.])
tensor([3., 4.]) tensor([33., 44.])
tensor([5.]) tensor([55.])


In [1]:
import os 
import torch
import torch.nn as nn 
from torch.utils.data import DataLoader, Dataset
import pandas as pd 

# Example: 
'''
1- Reading Iris data set 
2- Making CostumDataSet 
3- Using it with DataLoader
3-
'''
iris = pd.read_csv("https://archive.ics.uci.edu//ml//machine-learning-databases//iris//iris.data", header = None)
mappings = {
   "Iris-setosa": 0,
   "Iris-versicolor": 1,
   "Iris-virginica": 2
}
iris.iloc[:,4] = iris.iloc[:,4].apply(lambda x: mappings[x])
print (iris.tail())
x = iris.iloc[:, 0:4].values
print (x.shape, type(x))
y = iris[4].values
print (y.shape, type(y))
#%%
x_train_tensor = torch.from_numpy(x)
y_train_tensor = torch.from_numpy(y)
#%%
class CustomDataset(Dataset):
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def __getitem__(self, index):
        return (self.x[index], self.y[index])

    def __len__(self):
        return len(self.x)
    
train = CustomDataset(x_train_tensor, y_train_tensor)
train_loader = DataLoader(dataset=train, batch_size=5, shuffle=False)
#%%
for i in train_loader: 
    print ((i))

       0    1    2    3  4
145  6.7  3.0  5.2  2.3  2
146  6.3  2.5  5.0  1.9  2
147  6.5  3.0  5.2  2.0  2
148  6.2  3.4  5.4  2.3  2
149  5.9  3.0  5.1  1.8  2
(150, 4) <class 'numpy.ndarray'>
(150,) <class 'numpy.ndarray'>
[tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.0000, 3.6000, 1.4000, 0.2000]], dtype=torch.float64), tensor([0, 0, 0, 0, 0])]
[tensor([[5.4000, 3.9000, 1.7000, 0.4000],
        [4.6000, 3.4000, 1.4000, 0.3000],
        [5.0000, 3.4000, 1.5000, 0.2000],
        [4.4000, 2.9000, 1.4000, 0.2000],
        [4.9000, 3.1000, 1.5000, 0.1000]], dtype=torch.float64), tensor([0, 0, 0, 0, 0])]
[tensor([[5.4000, 3.7000, 1.5000, 0.2000],
        [4.8000, 3.4000, 1.6000, 0.2000],
        [4.8000, 3.0000, 1.4000, 0.1000],
        [4.3000, 3.0000, 1.1000, 0.1000],
        [5.8000, 4.0000, 1.2000, 0.2000]], dtype=torch.float64), tensor([0, 0, 0, 0, 0]